series: Intermediate C++
title: Assertions
author:
  name: David Erbelding
  email: daviderbelding@gmail.com
  github: https://github.com/Erbelding
description: Use assertions to help find bugs in your code.
language: C++
tags:
  - Core
extra_resources:
connections:
  - series: Intermediate C++
    title: Macros
  - series: Basic C++
    title: C Strings